# -*- coding: utf-8 -*-
"""Medidas_Dispersão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aK3D0h4lFX6OyKagMRaYYSdaBjfjDn82
"""

#Desvio médio absoluto
import pandas as pd
import numpy as np
import seaborn as sns
import scipy
dados = pd.read_csv('dados.csv') # Leitura dos dados
type(dados)
dados.head()

df = pd.DataFrame(data={'Pedro' :[8,10,4,8,6,10,8],
                        'Victor': [10,2,0.5,1,3,9.5,10],
                         'Wandson': [7.5,8,7,8,8,8.5,7]},
                  index= ['Calculo I', 'Física I', 'Mat.Discreta I',
                          'Inglês','Programção I','Geo.Analitica',
                          'INTRODUÇÃO À ENG. DE COMPUTAÇÃO'])
df.rename_axis('Matérias',axis='columns',inplace=True)
df.mean()

#Criar o desvio Médio absoluto
notas_Victor = df[['Victor']] #FAZER UM DATAFRAME
notas_Victor

nota_media_victor = notas_Victor.mean() [0] #Passar só o valor
nota_media_victor

notas_Victor['Desvio'] = notas_Victor['Victor'] - nota_media_victor
notas_Victor

notas_Victor['Desvio'].sum()

notas_Victor['|Desvio|'] = notas_Victor['Desvio'].abs()
notas_Victor

notas_Victor['|Desvio|'].sum()

ax = notas_Victor['Victor'].plot(style='o')
ax.figure.set_size_inches(14,6)
ax.hlines(y = nota_media_victor, xmin=0, xmax = notas_Victor.shape[0]- 1 , colors='red')
for i in range(notas_Victor.shape[0]):
  ax.vlines(x = i,ymin = nota_media_victor, ymax = notas_Victor['Victor'][i], linestyles='dashed')
ax

# a reta vermelha representa a média e os pontos em azul representa os desvios em compração com a média.

#Desvio médio absoluto sem funções, só manipulação
notas_Victor[ '|Desvio|' ].mean()

#Desvio médio usando funções
desvio_médio_absoluto = notas_Victor['Victor'].mad()
desvio_médio_absoluto

#Variância
notas_Victor['(Desvio)^2']=notas_Victor['Desvio'].pow(2)
notas_Victor

#Variância amostral
notas_Victor['(Desvio)^2'].sum()/(len(notas_Victor)-1)

#Utilizando o pandas para variancia
variancia = notas_Victor['Desvio'].var()
variancia

#Desvio Padrão amostral  com uso do numpý
np.sqrt(variancia)

#Com o uso do pandas
desvio_padrao = notas_Victor['Victor'].std()
desvio_padrao

df.mean()

df.median()

df.mode()

df.std()