# -*- coding: utf-8 -*-
"""Medidas_Sepratrizes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14PaEQ3X22GLzTVsDJxUKwz46mEd99Jjt
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

dados = pd.read_csv('dados.csv')  # Leitura dos dados
type(dados)
dados.head() #Mostrar os primeiros dados

#QUARTIS
dados.Renda.quantile([0.25, 0.5 ,0.75])

[i /10 for i in range(1,10)]
#Crição de todos os decis
dados.Renda.quantile([i /10 for i in range(1,10)])

#Crição dos percintis
dados.Renda.quantile([i / 100 for i in range(1,100)])

#Gerando  o gráfico
ax = sns.distplot(dados.Idade,
                  hist_kws={'cumulative': True},
                  kde_kws = {'cumulative ': True })
ax.figures.set_size_inches(14,6)
ax.set_title('Distribuição de Frequencia Acumulada ', fontsize=18)
ax.set_ylable('Acumaldo', fontize=14)
ax.set_xlable('Anos', fontize=14)

