# -*- coding: utf-8 -*-
"""Medidas_Centrais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-vkRSMg-cUZJMDPg5gpiNvNM9da1dVmZ
"""

import pandas as pd
import numpy as np
import seaborn as sns
import scipy
dados = pd.read_csv('dados.csv') # Leitura dos dados
type(dados)
dados.head()

#Medidas de Tendências Central
#DataFrame
df = pd.DataFrame(data={'Pedro' :[8,10,4,8,6,10,8],
                        'Victor': [10,2,0.5,1,3,9.5,10],
                         'Wandson': [7.5,8,7,8,8,8.5,7]},
                  index= ['Calculo I', 'Física I', 'Mat.Discreta I',
                          'Inglês','Programção I','Geo.Analitica',
                          'INTRODUÇÃO À ENG. DE COMPUTAÇÃO'])
df.rename_axis('Matérias',axis='columns',inplace=True)
df

df['Pedro'].mean() #Calculara a média
dados.Renda.mean()

#Calculara a renda média por sexo
renda_sexo = dados.groupby(['Sexo'])['Renda'].mean()
renda_sexo.rename(index={0:'Masculino ', 1:'Feminino'}, inplace=True )
renda_sexo